# Generated by Django 5.0.1 on 2024-04-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='object_data',
            field=models.JSONField(),
        ),
    ]
