# Generated by Django 5.0.1 on 2024-05-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoobject',
            name='object_data',
            field=models.JSONField(blank=True),
        ),
    ]
