# Generated by Django 5.0.1 on 2024-04-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mymodel_object_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='GeoObject',
        ),
    ]
